# Generated by Django 3.1.2 on 2021-02-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_auto_20210207_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
