# Generated by Django 3.1.2 on 2021-02-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_auto_20210207_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='account_id',
        ),
    ]
